version: "3.3"

services: 
  ldap-service:
    image: osixia/openldap
    networks: 
      - ldap-network
    env_file:
      - ldap.env
  phpldapadmin:
    image: odk/phpldapadmin
    ports:
      - "${PHP_LDAPADMIN_PORT:-40000}:443"
    networks: 
      - ldap-network
    env_file:
      - ldap.env

networks:
  ldap-network:
    external: 
      name: ${LDAP_NETWORK:-ldap-network}
