version: "3.3"

services: 
  # use extends instead when it becomes available
  # ldap-service and phpldapadmin should be the same as in docker-compose.yml
  ldap-service:
    image: osixia/openldap
    networks: 
      - ldap-network
    env_file:
      - ldap.env
  phpldapadmin:
    image: odk/phpldapadmin
    ports:
      - "${PHP_LDAPADMIN_PORT:-40000}:443"
    networks: 
      - ldap-network
    env_file:
      - ldap.env
  sync:
    image: odk/sync_endpoint
    networks: 
      - ldap-network
      - psql-network
    ports:
      - "80:8080"
    env_file:
      - sync.env
    # configs:
      # - org.opendatakit.sync.ldapcert
      # - org.opendatakit.aggregate.logging.properties
    secrets:
      - org.opendatakit.aggregate.security.properties
      - org.opendatakit.aggregate.jdbc.properties

networks:
  ldap-network:
    external: 
      name: ${LDAP_NETWORK:-ldap-network}
  psql-network:
    external:
      name: ${POSTGRES_NETWORK:-psql-network}

#configs:
  # org.opendatakit.sync.ldapcert:
    # external: true
  # org.opendatakit.aggregate.logging.properties:
    # external: true

secrets:
  org.opendatakit.aggregate.security.properties:
    external: true
  org.opendatakit.aggregate.jdbc.properties:
    external: true
